// Antigravity AI Editor Simulation

const CODE_EXAMPLES = {
  'agent_config.py': `
<span class="cmt"># AI Agent Configuration for Antigravity Swarm</span>
<span class="kw">import</span> <span class="var">antigravity</span> <span class="kw">as</span> <span class="var">ag</span>

<span class="kw">class</span> <span class="fn">ArchitectAgent</span>(<span class="var">ag.Agent</span>):
    <span class="kw">def</span> <span class="fn">__init__</span>(<span class="var">self</span>):
        <span class="var">self</span>.model = <span class="str">"gemini-3-pro"</span> <span class="cmt"># 1M Token Context</span>
        <span class="var">self</span>.role = <span class="str">"system_design"</span>
        <span class="var">self</span>.thinking_level = <span class="str">"high"</span> <span class="cmt"># Deep Think Mode</span>

<span class="kw">class</span> <span class="fn">EngineerAgent</span>(<span class="var">ag.Agent</span>):
    <span class="kw">def</span> <span class="fn">__init__</span>(<span class="var">self</span>):
        <span class="var">self</span>.model = <span class="str">"gpt-oss-120b"</span> <span class="cmt"># Optimized for Coding</span>
        <span class="var">self</span>.capabilities = [<span class="str">"code_gen"</span>, <span class="str">"debug"</span>, <span class="str">"review"</span>]

<span class="cmt"># Initialize Swarm Orchestration</span>
<span class="var">swarm</span> = <span class="var">ag.Swarm</span>([<span class="fn">ArchitectAgent</span>(), <span class="fn">EngineerAgent</span>()])
<span class="var">swarm</span>.<span class="fn">deploy</span>()
`,
  'readme.md': `
# Project Antigravity
Generated by **Gemini 3 Pro**

## Status
- [x] Architecture Planning
- [x] Core Implementation
- [ ] Deployment

This project utilizes the latest **Agentic Workflow** standards.
`
};

// State
let currentFile = 'agent_config.py';
let isAIWriting = false;

// DOM Elements
const codeContent = document.getElementById('code-content');
const lineNumbers = document.getElementById('line-numbers');
const chatArea = document.getElementById('chat-area');
const aiSidebar = document.getElementById('ai-sidebar');

// Initialization
function initEditor() {
  updateLineNumbers();
  loadContent(currentFile);
  
  // Simulate AI Welcome
  setTimeout(() => {
    addChatMessage('ai', "Hello! I'm your Gemini 3 Pro assistant. I've initialized the project structure. Ready to code?");
    toggleSidebar(true);
  }, 1000);
}

function loadContent(filename) {
  currentFile = filename;
  const rawHTML = CODE_EXAMPLES[filename] || '';
  
  // Update Tabs
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  const activeTab = Array.from(document.querySelectorAll('.tab')).find(t => t.textContent.includes(filename));
  if (activeTab) activeTab.classList.add('active');

  // Render content
  codeContent.innerHTML = rawHTML + '<span class="cursor"></span>';
  updateLineNumbers();
}

function updateLineNumbers() {
  const lines = (CODE_EXAMPLES[currentFile] || '').split('\n').length;
  lineNumbers.innerHTML = Array(lines).fill(0).map((_, i) => `<div>${i + 1}</div>`).join('');
}

function addChatMessage(role, text) {
  const msgDiv = document.createElement('div');
  msgDiv.className = `message ${role}`;
  msgDiv.textContent = text;
  chatArea.appendChild(msgDiv);
  chatArea.scrollTop = chatArea.scrollHeight;
}

function toggleSidebar(forceOpen = null) {
  if (forceOpen !== null) {
      aiSidebar.classList.toggle('open', forceOpen);
  } else {
      aiSidebar.classList.toggle('open');
  }
}

// Simulate AI Coding
async function runAgentDemo() {
  if (isAIWriting) return;
  isAIWriting = true;
  
  addChatMessage('user', "Add a deployment function to the agent config.");
  await new Promise(r => setTimeout(r, 800));
  addChatMessage('ai', "Planning implementation... Adding `deploy_to_cloud` method using Google Cloud SDK.");
  
  const newCode = `

    <span class="kw">async def</span> <span class="fn">deploy_to_cloud</span>(<span class="var">self</span>, <span class="var">target</span>):
        <span class="var">console</span>.<span class="fn">log</span>(<span class="str">"Deploying..."</span>)
        <span class="kw">await</span> <span class="var">ag.cloud</span>.<span class="fn">push</span>(<span class="var">target</span>)
        <span class="kw">return</span> <span class="var">True</span>`;
        
  // Typewriter effect
  const lines = newCode.split('\n');
  for (let line of lines) {
      codeContent.innerHTML += line;
      updateLineNumbers();
      codeContent.scrollTop = codeContent.scrollHeight;
      await new Promise(r => setTimeout(r, 100)); // typing speed
  }
  
  addChatMessage('ai', "Done! Deployment logic added.");
  isAIWriting = false;
}

// Event Listeners
document.getElementById('ai-trigger').addEventListener('click', () => toggleSidebar());
document.getElementById('run-agent-btn').addEventListener('click', runAgentDemo);

// File Switch Simulation
document.querySelectorAll('.file-item').forEach(item => {
  item.addEventListener('click', (e) => {
    const file = e.currentTarget.innerText.trim();
    if (CODE_EXAMPLES[file.toLowerCase()]) { // Simple mapping
       loadContent(file.toLowerCase());
    }
  });
});

initEditor();
