// Antigravity AI Editor Simulation

const CODE_EXAMPLES = {
  'agent_config.py': `
<span class="cmt"># AI Agent Configuration for Antigravity Swarm</span>
<span class="kw">import</span> <span class="var">antigravity</span> <span class="kw">as</span> <span class="var">ag</span>

<span class="kw">class</span> <span class="fn">ArchitectAgent</span>(<span class="var">ag.Agent</span>):
    <span class="kw">def</span> <span class="fn">__init__</span>(<span class="var">self</span>):
        <span class="var">self</span>.model = <span class="str">"gemini-3-pro"</span> <span class="cmt"># 1M Token Context</span>
        <span class="var">self</span>.role = <span class="str">"system_design"</span>
        <span class="var">self</span>.thinking_level = <span class="str">"high"</span> <span class="cmt"># Deep Think Mode</span>

<span class="kw">class</span> <span class="fn">EngineerAgent</span>(<span class="var">ag.Agent</span>):
    <span class="kw">def</span> <span class="fn">__init__</span>(<span class="var">self</span>):
        <span class="var">self</span>.model = <span class="str">"gpt-oss-120b"</span> <span class="cmt"># Optimized for Coding</span>
        <span class="var">self</span>.capabilities = [<span class="str">"code_gen"</span>, <span class="str">"debug"</span>, <span class="str">"review"</span>]

<span class="cmt"># Initialize Swarm Orchestration</span>
<span class="var">swarm</span> = <span class="var">ag.Swarm</span>([<span class="fn">ArchitectAgent</span>(), <span class="fn">EngineerAgent</span>()])
<span class="var">swarm</span>.<span class="fn">deploy</span>()
`,
  'readme.md': `
# Project Antigravity
Generated by **Gemini 3 Pro**

## Status
- [x] Architecture Planning
- [x] Core Implementation
- [ ] Deployment

This project utilizes the latest **Agentic Workflow** standards.
`
};

// State
let currentFile = 'agent_config.py';
let isAIWriting = false;

// DOM Elements
const codeContent = document.getElementById('code-content');
const lineNumbers = document.getElementById('line-numbers');
const chatArea = document.getElementById('chat-area');
const aiSidebar = document.getElementById('ai-sidebar');

// Initialization
function initEditor() {
  updateLineNumbers();
  loadContent(currentFile);
  
  // Simulate AI Welcome
  setTimeout(() => {
    addChatMessage('ai', "Hello! I'm your Gemini 3 Pro assistant. I've initialized the project structure. Ready to code?");
    toggleSidebar(true);
  }, 1000);
}

function loadContent(filename) {
  currentFile = filename;
  const rawHTML = CODE_EXAMPLES[filename] || '';
  
  // Update Tabs
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  const activeTab = Array.from(document.querySelectorAll('.tab')).find(t => t.textContent.includes(filename));
  if (activeTab) activeTab.classList.add('active');

  // Render content
  codeContent.innerHTML = rawHTML + '<span class="cursor"></span>';
  updateLineNumbers();
}

function updateLineNumbers() {
  const lines = (CODE_EXAMPLES[currentFile] || '').split('\n').length;
  lineNumbers.innerHTML = Array(lines).fill(0).map((_, i) => `<div>${i + 1}</div>`).join('');
}

function addChatMessage(role, text) {
  const msgDiv = document.createElement('div');
  msgDiv.className = `message ${role}`;
  msgDiv.textContent = text;
  chatArea.appendChild(msgDiv);
  chatArea.scrollTop = chatArea.scrollHeight;
}

function toggleSidebar(forceOpen = null) {
  if (forceOpen !== null) {
      aiSidebar.classList.toggle('open', forceOpen);
  } else {
      aiSidebar.classList.toggle('open');
  }
}

// Smart Model Routing Algorithm (Phase 11) & Artifacts (Phase 13)
async function runAgent() {
  const input = document.querySelector('.ai-input');
  const chatArea = document.getElementById('chat-area');
  const userText = input.value;
  if (!userText) return;

  // 1. User Message
  addChatMessage('user', userText);
  input.value = '';

  // 2. Determine Model via "Architecture" (Settings)
  const preferredModel = localStorage.getItem('ag_model') || 'gemini';
  const thinkingLevel = parseInt(localStorage.getItem('ag_thinking') || '8');
  
  // Routing Decision
  let activeModel = preferredModel;
  let reason = "User Preference";

  // "Smart Router" Simulation
  if (userText.length < 15 && thinkingLevel < 5 && preferredModel === 'gemini') {
      activeModel = 'gpt';
      reason = "Optimized for Speed (Low Latency)";
  }

  const modelName = activeModel === 'gemini' ? "Gemini 3 Pro" : "GPT-OSS 120B";
  
  // 3. Routing Notification
  const routingMsg = document.createElement('div');
  routingMsg.style.cssText = "font-size: 0.75rem; color: #666; margin: 10px 0; font-family: 'JetBrains Mono'; text-align: center;";
  routingMsg.innerText = `⚡ Routing to ${modelName} via MCP... (${reason})`;
  chatArea.appendChild(routingMsg);

  // 4. Save to Swarm Store (Phase 13)
  if (window.AGStore) {
      window.AGStore.addTask(userText, modelName);
      console.log("Task pushed to Swarm Memory:", userText);
  }

  // 5. AI Response Simulation
  const delay = activeModel === 'gemini' ? 2000 : 800; // Gemini "Thinks", GPT is fast
  
  await new Promise(r => setTimeout(r, delay));

  // Artifact Logic (Phase 13 & 15)
  let content = "";
  let isArtifact = false;
  
  if (userText.toLowerCase().includes('page') || userText.toLowerCase().includes('html') || userText.toLowerCase().includes('ui')) {
      isArtifact = true;
      content = `<strong>Generated Artifact.</strong><br>I have created a UI preview based on your request. Switching to Preview Mode and <strong>saving to Gallery</strong>...`;
  } else {
      if (activeModel === 'gemini') {
          content = `<strong>Analyzed Request.</strong><br>Reasoning Depth: Level ${thinkingLevel}.<br>I will now implement the changes based on the ${activeModel} architecture.`;
      } else {
          content = `<strong>Instant Generate.</strong><br>Executing code generation task for: "${userText}"`;
  }
}

  const aiMsg = document.createElement('div');
  aiMsg.className = 'message ai';
  aiMsg.innerHTML = `
    <div style="margin-bottom: 5px; font-size: 0.8rem; color: #aaa; display: flex; align-items: center; gap: 6px;">
      ${modelName} 
      <span style="font-size: 0.6rem; border: 1px solid #444; padding: 1px 4px; border-radius: 4px;">${activeModel.toUpperCase()}</span>
    </div>
    <div>${content}</div>
  `;
  chatArea.appendChild(aiMsg);
  chatArea.scrollTop = chatArea.scrollHeight;
  routingMsg.innerText = `✔ Executed by ${modelName} in ${delay}ms`;
  routingMsg.style.color = activeModel === 'gemini' ? '#7c4dff' : '#00e676';

  // Trigger Artifact Preview & Save
  if (isArtifact) {
      renderArtifact(userText, modelName);
  }
}

// Artifact Preview Renderer (Generative UI Engine)
function renderArtifact(prompt, modelName) {
    const codeContent = document.getElementById('code-content');
    
    // Clear current content
    codeContent.innerHTML = '';
    
    // 1. Generate Simulated HTML Code
    let htmlCode = `
      <style>
        body { font-family: 'Inter', sans-serif; padding: 40px; background: #f5f5f5; color: #333; }
        .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1 { color: #111; }
        button { background: #000; color: #fff; border: 0; padding: 10px 20px; border-radius: 6px; cursor: pointer; }
      </style>
      <div class="container">
        <h1>Generated Artifact</h1>
        <p>Prompt: ${prompt}</p>
        <p>Generated by: ${modelName}</p>
        <hr style="margin: 20px 0; border: 0; border-top: 1px solid #eee;">
    `;

    if (prompt.includes('login')) {
      htmlCode += `
        <h2>Welcome Back</h2>
        <div style="display: flex; flex-direction: column; gap: 15px; max-width: 300px;">
          <input type="email" placeholder="Email Address" style="padding: 10px; border: 1px solid #ccc; border-radius: 6px;">
          <input type="password" placeholder="Password" style="padding: 10px; border: 1px solid #ccc; border-radius: 6px;">
          <button>Sign In</button>
        </div>
      `;
    } else if (prompt.includes('dashboard')) {
      htmlCode += `
        <h2>Analytics Dashboard</h2>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 20px;">
          <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; border: 1px solid #bbf7d0;">
            <h3>Users</h3>
            <p style="font-size: 2rem; font-weight: bold;">12,543</p>
          </div>
          <div style="background: #eff6ff; padding: 20px; border-radius: 8px; border: 1px solid #bfdbfe;">
            <h3>Revenue</h3>
            <p style="font-size: 2rem; font-weight: bold;">$45,200</p>
          </div>
        </div>
      `;
    } else {
      htmlCode += `<p>Content generated for request: "${prompt}"</p><button>Action Button</button>`;
    }

    htmlCode += `</div>`; // Close container

    // 2. Save Code to Store (Phase 15 Feature)
    if (window.AGStore) {
        // We need to find the latest task to update it, or just add a new "Artifact Task"
        // For simplicity, we'll just add a new Task with the code *explicitly*
        window.AGStore.addTask(prompt, modelName, htmlCode);
        console.log("Artifact Code Saved to Gallery.");
    }

    // 3. Render in Preview Pane
    const previewContainer = document.createElement('div');
    previewContainer.style.cssText = "width:100%; height:100%; background:white; color:black; padding:0; box-sizing:border-box; overflow:hidden;";
    const iframe = document.createElement('iframe');
    iframe.style.cssText = "width:100%; height:100%; border:none;";
    iframe.srcdoc = htmlCode;
    previewContainer.appendChild(iframe);
    
    codeContent.appendChild(previewContainer);
}

// Event Listeners
document.getElementById('ai-trigger').addEventListener('click', () => toggleSidebar());
document.getElementById('run-agent-btn').addEventListener('click', runAgent);

// File Switch Simulation
document.querySelectorAll('.file-item').forEach(item => {
  item.addEventListener('click', (e) => {
    const file = e.currentTarget.innerText.trim();
    if (CODE_EXAMPLES[file.toLowerCase()]) { // Simple mapping
       loadContent(file.toLowerCase());
    }
  });
});

initEditor();
